import type { Metadata } from "next";
import { Sora, Work_Sans } from "next/font/google";
import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
})

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-Work-Sans",
})

export const metadata: Metadata = {
  title: "Thom Gomes",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: RootLayoutProps) {

  return (
    <html>
      <body
        className={`${sora.variable} ${workSans.variable} antialiased`}
      >
         {children}
      </body>
    </html>
  );
}
