import type { Metadata } from "next";
import { Sora, Work_Sans } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-Work-Sans",
});

export const metadata: Metadata = {
  title: "Thom Gomes",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${sora.variable} ${workSans.variable} antialiased`}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
