import type { Metadata } from "next";
import { Sora, Work_Sans } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "@/components/theme-provider";
import CustomCursor from "@/components/gsap/custom-cursor";
import SmoothScroll from "@/components/gsap/smooth-scroll";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-Work-Sans",
});

export const metadata: Metadata = {
  title: "Thom Gomes",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${sora.variable} ${workSans.variable} antialiased`}>
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CustomCursor/>
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
