import type { Metadata } from "next";
import { Sora, Work_Sans } from "next/font/google";
import "../globals.css";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
})

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-Work-Sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${sora.variable} ${workSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
